Player.create(name: 'Neymar', team: 'PSG', cost: 7.91)
Player.create(name: 'Raheem Sterling', team: 'Manchester City', cost: 6.93)
Player.create(name: 'Jadon Sancho', team: 'Borussia Dortmund', cost: 6.91)
Player.create(name: 'Kylian Mbappe', team: 'PSG', cost: 6.48)
Player.create(name: 'Trent Alexander-Arnold', team: 'Liverpool', cost: 6.40)
Player.create(name: 'Lionel Messi', team: 'Barcelona', cost: 6.08)
Player.create(name: 'Paul Pogba', team: 'Manchester United', cost: 5.02)
Player.create(name: 'Harry Kane', team: 'Tottenham Hotspur', cost: 5.91)
Player.create(name: 'Kevin DeBruyne', team: 'Manchester City', cost: 5.13)
Player.create(name: 'Marcus Rashford', team: 'Manchester United', cost: 4.91)
Player.create(name: 'James Maddison', team: 'Leicester City', cost: 4.91)
Player.create(name: 'Toni Kroos', team: 'Real Madrid', cost: 4.82)
Player.create(name: 'Memphis Depay', team: 'Lyon', cost: 4.63)
Player.create(name: 'Joshua Kimmich', team: 'Bayern Munchen', cost: 4.27)
Player.create(name: 'Mohamed Salah', team: 'Liverpool', cost: 4.15)
Player.create(name: 'Erling Braut Haaland', team: 'Red Bull Salzburg', cost: 4.09)
Player.create(name: 'Eden Hazard', team: 'Real Madrid', cost: 3.94)
Player.create(name: 'Timo Werner', team: 'RB Leipzig', cost: 3.92)
Player.create(name: 'Callum Hudson-Odoi', team: 'Chelsea', cost: 3.82)
Player.create(name: 'Joao Felix', team: 'Athletico Madrid', cost: 3.75)
Player.create(name: 'Mason Greenwood', team: 'Manchester United', cost: 3.62)
Player.create(name: 'Ansu Fati', team: 'Barcelona', cost: 3.57)
Player.create(name: 'Martin Odegaard', team: 'Real Sociedad', cost: 3.56)
Player.create(name: 'Kai Havertz', team: 'Bayer Leverkusen', cost: 3.56)
Player.create(name: 'Rodrygo', team: 'Real Madrid', cost: 3.55)
Player.create(name: 'Phil Foden', team: 'Manchester City', cost: 3.46)
Player.create(name: 'Jack Grealish', team: 'Aston Villa', cost: 3.32)
Player.create(name: 'Dele Alli', team: 'Tottenham Hotspur', cost: 3.21)
Player.create(name: 'Tammy Abraham', team: 'Chelsea', cost: 3.21)
Player.create(name: 'Serge Gnabry', team: 'Bayern Munchen', cost: 3.10)
Player.create(name: 'Sadio Mane', team: 'Liverpool', cost: 3.06)
Player.create(name: 'Reece James', team: 'Chelsea', cost: 3.02)
Player.create(name: 'Paulo Dybala', team: 'Juventus', cost: 3.00)
Player.create(name: 'Nicolas Pepe', team: 'Arsenal', cost: 2.99)
Player.create(name: 'Leroy Sane', team: 'Manchester City', cost: 2.97)
Player.create(name: 'Mason Mount', team: 'Chelsea', cost: 2.97)
Player.create(name: 'Luis Alberto', team: 'Lazio', cost: 2.96)
Player.create(name: 'Cristiano Ronaldo', team: 'Juventus', cost: 2.93)
Player.create(name: 'Fabian Ruiz', team: 'Napoli', cost: 2.88)
Player.create(name: 'Ben Chilwell', team: 'Leicester City', cost: 2.85)
